package com.jointem.dbhelper;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jointem.dbhelper.DownInfo;
import com.jointem.dbhelper.UserInfo;
import com.jointem.dbhelper.UserInfo2;

import com.jointem.dbhelper.DownInfoDao;
import com.jointem.dbhelper.UserInfoDao;
import com.jointem.dbhelper.UserInfo2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig userInfo2DaoConfig;

    private final DownInfoDao downInfoDao;
    private final UserInfoDao userInfoDao;
    private final UserInfo2Dao userInfo2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downInfoDaoConfig = daoConfigMap.get(DownInfoDao.class).clone();
        downInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        userInfo2DaoConfig = daoConfigMap.get(UserInfo2Dao.class).clone();
        userInfo2DaoConfig.initIdentityScope(type);

        downInfoDao = new DownInfoDao(downInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        userInfo2Dao = new UserInfo2Dao(userInfo2DaoConfig, this);

        registerDao(DownInfo.class, downInfoDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(UserInfo2.class, userInfo2Dao);
    }
    
    public void clear() {
        downInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        userInfo2DaoConfig.clearIdentityScope();
    }

    public DownInfoDao getDownInfoDao() {
        return downInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public UserInfo2Dao getUserInfo2Dao() {
        return userInfo2Dao;
    }

}
